"""
models/database.py
SQLAlchemy models for the Regulatory Change Monitor.

Tables:
  - regulations: raw regulatory items from all 4 sources
  - policy_impacts: which policies are affected by which regulation
  - memos: compliance memos generated by draft_agent
"""

from datetime import datetime
from sqlalchemy import (
    create_engine,
    Column,
    Index,
    Integer,
    String,
    Text,
    DateTime,
    Boolean,
    ForeignKey,
)
from sqlalchemy.orm import declarative_base, relationship, sessionmaker

from config.config import DATABASE_URL

Base = declarative_base()


class Regulation(Base):
    __tablename__ = "regulations"

    id = Column(Integer, primary_key=True, autoincrement=True)

    # Source identification
    source = Column(String(50), nullable=False)          # federal_register, tdi, cdi, ofac
    source_id = Column(String(200), nullable=True)        # FR document number, bulletin number, etc.
    source_url = Column(Text, nullable=True)              # link to original document

    # Content
    title = Column(Text, nullable=False)
    text = Column(Text, nullable=True)                    # full text or summary
    regulation_type = Column(String(50), nullable=True)   # Rule, Proposed Rule, Notice, Bulletin, Sanctions
    agency = Column(String(200), nullable=True)           # issuing agency name
    published_date = Column(DateTime, nullable=True)      # date published/issued

    # Classification by filter_agent
    relevant = Column(Boolean, nullable=True)             # is it relevant to life insurance?
    state = Column(String(10), nullable=True)             # TX, CA, BOTH
    severity = Column(String(20), nullable=True)          # critical, high, medium, low
    filter_reason = Column(Text, nullable=True)           # why filter_agent classified it this way

    # Processing status
    status = Column(String(30), default="pending")        # pending, classified, rejected, impact_mapped, memo_generated

    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Indexes for dashboard query performance
    __table_args__ = (
        Index("ix_regulations_relevant", "relevant"),
        Index("ix_regulations_severity", "severity"),
        Index("ix_regulations_state", "state"),
        Index("ix_regulations_source", "source"),
        Index("ix_regulations_published_date", "published_date"),
        Index("ix_regulations_status", "status"),
        Index("ix_regulations_relevant_severity_state", "relevant", "severity", "state"),
    )

    # Relationships
    impacts = relationship("PolicyImpact", back_populates="regulation", cascade="all, delete-orphan")
    memo = relationship("Memo", back_populates="regulation", uselist=False, cascade="all, delete-orphan")


class PolicyImpact(Base):
    __tablename__ = "policy_impacts"

    id = Column(Integer, primary_key=True, autoincrement=True)
    regulation_id = Column(Integer, ForeignKey("regulations.id"), nullable=False)

    # Policy identification
    policy_id = Column(String(10), nullable=False)        # P01, P02, ..., R01, R02, ...
    policy_name = Column(String(200), nullable=False)     # Access Term Life, etc.
    form_number = Column(String(100), nullable=True)      # ICC23-51448, etc.

    # Impact details
    affected_state = Column(String(10), nullable=False)   # TX, CA, BOTH
    affected_clause = Column(Text, nullable=True)         # specific clause impacted
    impact_description = Column(Text, nullable=True)      # how this regulation affects this policy

    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow)

    # Relationships
    regulation = relationship("Regulation", back_populates="impacts")


class Memo(Base):
    __tablename__ = "memos"

    id = Column(Integer, primary_key=True, autoincrement=True)
    regulation_id = Column(Integer, ForeignKey("regulations.id"), nullable=False, unique=True)

    # Memo content
    memo_text = Column(Text, nullable=False)              # full compliance memo from draft_agent

    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow)

    # Relationships
    regulation = relationship("Regulation", back_populates="memo")


# ── Engine and Session ────────────────────────────────────

engine = create_engine(DATABASE_URL, echo=False)
SessionLocal = sessionmaker(bind=engine)


def init_db():
    """Create all tables. Run once."""
    Base.metadata.create_all(engine)
    print(f"[OK] Database initialized at {DATABASE_URL}")
    print(f"     Tables: {', '.join(Base.metadata.tables.keys())}")


def get_session():
    """Get a new database session."""
    return SessionLocal()


if __name__ == "__main__":
    init_db()